DEFAULT_CIF_SUFFIX = ".cif"
DEFAULT_DSSP_SUFFIX = ".dssp"
DEFAULT_HELIX_MIN_LENGTH = 3
DEFAULT_STRAND_MIN_LENGTH = 2
MIN_LENGTH_LUR = 5
AF_FRAGMENT_MAX_RESIDUES = 1400
AF_FRAGMENT_OVERLAP_WINDOW = 200
